#!/usr/bin/env python3
"""Emit the colour-science constants the Swift engine needs as generated Swift source.

The reference engine calls into colour-science for colour-matching functions, illuminant
spectral distributions, RGB colourspace matrices and chromatic adaptation. None of that
exists on iOS, so every table the runtime touches is extracted here, once, from the pinned
oracle environment.

Only *tables* are emitted. Transfer functions stay as formulas in Swift and are gated
against colour-science by Tools/parity/generate_goldens.py instead, so a typo in a
piecewise breakpoint fails a test rather than silently shifting every render.

Usage:  Tools/parity/extract_colour_tables.py [--check]
        --check exits non-zero if the committed file is stale (used by CI).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import colour
import numpy as np

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "Sources" / "SpektraFilm" / "Generated" / "ColourTables.swift"

SHAPE = colour.SpectralShape(380, 780, 5)

# Every RGB colourspace the reference GUI exposes (spektrafilm_gui/options.py:RGBColorSpaces).
COLOURSPACES = [
    "sRGB",
    "DCI-P3",
    "Display P3",
    "Adobe RGB (1998)",
    "ITU-R BT.2020",
    "ProPhoto RGB",
    "ACES2065-1",
]

# Illuminants reachable from the 28 bundled profiles plus the colourspace whitepoints.
# 'TH-KG3' and 'TH-KG3-L' are synthesised in Swift (blackbody x filter), not tabulated.
CIE_ILLUMINANTS = ["D50", "D55", "D65"]
LIGHT_SOURCES = {"Incandescent": "T", "Kinoton 75P": "K75P"}

# Swift identifier -> colour-science transform name.
CATS = {"cat02": "CAT02", "cat16": "CAT16", "bradford": "Bradford", "vonKries": "Von Kries"}


def f(x: float) -> str:
    """Round-trippable Swift Double literal."""
    v = float(x)
    if np.isnan(v):
        return "Double.nan"
    return repr(v)


def vector(values) -> str:
    return "[" + ", ".join(f(v) for v in np.asarray(values).ravel()) + "]"


def matrix3(m) -> str:
    m = np.asarray(m, dtype=float).reshape(3, 3)
    rows = ", ".join("[" + ", ".join(f(v) for v in row) + "]" for row in m)
    return f"[{rows}]"


def wrapped_table(name: str, values, per_line: int = 6) -> list[str]:
    """A [Double] literal broken over several lines so the file stays reviewable."""
    flat = [f(v) for v in np.asarray(values).ravel()]
    lines = [f"    {name}: [Double] = ["]
    for i in range(0, len(flat), per_line):
        lines.append("        " + ", ".join(flat[i : i + per_line]) + ",")
    lines.append("    ]")
    return lines


def aligned(sd) -> np.ndarray:
    return sd.copy().align(SHAPE).values


def build() -> str:
    wl = SHAPE.wavelengths
    n = len(wl)

    cmfs = colour.MSDS_CMFS["CIE 1931 2 Degree Standard Observer"].copy().align(SHAPE).values
    lms = (
        colour.colorimetry.MSDS_CMFS_LMS["Stockman & Sharpe 2 Degree Cone Fundamentals"]
        .copy()
        .align(SHAPE)
        .values
    )
    assert cmfs.shape == (n, 3) and lms.shape == (n, 3), (cmfs.shape, lms.shape)

    L: list[str] = []
    L.append("// Generated by Tools/parity/extract_colour_tables.py — do not edit.")
    L.append(f"// Source: colour-science {colour.__version__}, spectral shape"
             f" {int(SHAPE.start)}–{int(SHAPE.end)} nm step {int(SHAPE.interval)} nm.")
    L.append("// Regenerate with `make tables`; CI fails if this file drifts from the extractor.")
    L.append("")
    L.append("/// Spectral and colourimetric constants lifted from colour-science.")
    L.append("///")
    L.append("/// Tabulated rather than computed because the reference engine reads them from")
    L.append("/// colour-science's datasets, and any resampling we did ourselves would move the")
    L.append("/// numbers. Row-major throughout: spectral tables are `[wavelength][channel]`")
    L.append("/// flattened, so channel `c` of wavelength index `i` is at `i * 3 + c`.")
    L.append("public enum ColourTables {")
    L.append("")
    L.append(f"    /// Wavelengths in nm: {int(SHAPE.start)}…{int(SHAPE.end)} step"
             f" {int(SHAPE.interval)}, {n} samples.")
    L.append(f"    public static let wavelengthCount = {n}")
    L.append(f"    public static let wavelengthStart = {f(SHAPE.start)}")
    L.append(f"    public static let wavelengthInterval = {f(SHAPE.interval)}")
    L.append("")
    L.append("    // MARK: - Observers")
    L.append("")
    L.append("    /// CIE 1931 2° standard observer x̄ȳz̄, flattened [wavelength][xyz].")
    L.extend(wrapped_table("public static let cie1931_2deg", cmfs))
    L.append("")
    L.append("    /// Stockman & Sharpe 2° cone fundamentals, flattened [wavelength][lms].")
    L.append("    /// Used by the Hanatos-2025 sensitivity adaptation.")
    L.extend(wrapped_table("public static let stockmanSharpe2degLMS", lms))
    L.append("")
    L.append("    // MARK: - Illuminants")
    L.append("")
    L.append("    /// Relative spectral power distributions, unnormalised, as colour-science")
    L.append("    /// aligns them to the engine's spectral shape. `Illuminant.spectrum`")
    L.append("    /// applies the reference engine's mean normalisation on top.")
    for name in CIE_ILLUMINANTS:
        L.extend(wrapped_table(f"public static let illuminant{name}",
                               aligned(colour.SDS_ILLUMINANTS[name])))
        L.append("")
    for src, tag in LIGHT_SOURCES.items():
        ident = tag.replace("-", "")
        L.append(f"    /// colour-science light source {src!r}, profile tag {tag!r}.")
        L.extend(wrapped_table(f"public static let lightSource{ident}",
                               aligned(colour.SDS_LIGHT_SOURCES[src])))
        L.append("")
    L.append("    // MARK: - Chromatic adaptation")
    L.append("")
    L.append("    /// Cone-response matrices. CAT02 is colour-science's default for")
    L.append("    /// `XYZ_to_RGB`/`RGB_to_RGB`, so it is the one the scanning stage hits;")
    L.append("    /// CAT16 is named explicitly by the spectral-upsampling stage.")
    for ident, cat in CATS.items():
        m = colour.adaptation.CHROMATIC_ADAPTATION_TRANSFORMS[cat]
        L.append(f"    public static let {ident}: [[Double]] = {matrix3(m)}")
    L.append("")
    L.append("    // MARK: - RGB colourspaces")
    L.append("")
    L.append("    /// Primaries, whitepoint and both conversion matrices, taken from")
    L.append("    /// colour-science rather than recomputed from the primaries: several")
    L.append("    /// colourspaces ship published matrices that differ from a fresh")
    L.append("    /// derivation in the last few digits.")
    L.append("    public struct Colourspace: Sendable {")
    L.append("        public let name: String")
    L.append("        public let whitepoint: (x: Double, y: Double)")
    L.append("        public let toXYZ: [[Double]]")
    L.append("        public let fromXYZ: [[Double]]")
    L.append("        public let transfer: TransferFunction")
    L.append("    }")
    L.append("")
    L.append("    public static let colourspaces: [Colourspace] = [")
    for name in COLOURSPACES:
        cs = colour.RGB_COLOURSPACES[name]
        wp = np.asarray(cs.whitepoint, dtype=float)
        transfer = TRANSFER[name]
        L.append("        Colourspace(")
        L.append(f"            name: {name!r}".replace("'", '"') + ",")
        L.append(f"            whitepoint: (x: {f(wp[0])}, y: {f(wp[1])}),")
        L.append(f"            toXYZ: {matrix3(cs.matrix_RGB_to_XYZ)},")
        L.append(f"            fromXYZ: {matrix3(cs.matrix_XYZ_to_RGB)},")
        L.append(f"            transfer: .{transfer}")
        L.append("        ),")
    L.append("    ]")
    L.append("")
    L.append("    // MARK: - Perceptual spaces")
    L.append("")
    L.append("    /// Oklab: XYZ(D65) → LMS, then the non-linear LMS' → Lab matrix (Björn Ottosson).")
    ok = colour.models.oklab
    L.append(f"    public static let oklabXYZToLMS: [[Double]] = {matrix3(ok.MATRIX_1_XYZ_TO_LMS)}")
    L.append(f"    public static let oklabLMSToXYZ: [[Double]] = {matrix3(ok.MATRIX_1_LMS_TO_XYZ)}")
    L.append(f"    public static let oklabLMSPToLab: [[Double]] = {matrix3(ok.MATRIX_2_LMS_TO_LAB)}")
    L.append(f"    public static let oklabLabToLMSP: [[Double]] = {matrix3(ok.MATRIX_2_LAB_TO_LMS)}")
    L.append("")
    L.append("    /// Jzazbz, Safdar et al. 2017 parameterisation (colour-science's default).")
    jzm = colour.models.jzazbz
    jz = jzm.CONSTANTS_JZAZBZ_SAFDAR2017
    for key in ("b", "g", "d", "d_0", "m_1", "m_2", "c_1", "c_2", "c_3"):
        L.append(f"    public static let jzazbz_{key} = {f(jz[key])}")
    L.append(f"    public static let jzazbzXYZToLMS: [[Double]] = {matrix3(jzm.MATRIX_JZAZBZ_XYZ_TO_LMS)}")
    L.append(f"    public static let jzazbzLMSToXYZ: [[Double]] = {matrix3(jzm.MATRIX_JZAZBZ_LMS_TO_XYZ)}")
    L.append("    public static let jzazbzLMSPToIzAzBz: [[Double]] = "
             f"{matrix3(jzm.MATRIX_JZAZBZ_LMS_P_TO_IZAZBZ_SAFDAR2017)}")
    L.append("    public static let jzazbzIzAzBzToLMSP: [[Double]] = "
             f"{matrix3(jzm.MATRIX_JZAZBZ_IZAZBZ_TO_LMS_P_SAFDAR2017)}")
    L.append("")
    L.append("    /// CAM16 cone response and its inverse (Li et al. 2017).")
    L.append(f"    public static let cam16: [[Double]] = "
             f"{matrix3(colour.appearance.cam16.MATRIX_16)}")
    L.append(f"    public static let cam16Inverse: [[Double]] = "
             f"{matrix3(colour.appearance.cam16.MATRIX_INVERSE_16)}")
    L.append("    /// CAM16-UCS reuses the CAM02-UCS coefficients of Luo et al. 2006, which is")
    L.append("    /// what `colour.XYZ_to_CAM16UCS` defaults to.")
    ucs = colour.models.cam02_ucs.COEFFICIENTS_UCS_LUO2006["CAM02-UCS"]
    L.append(f"    public static let cam16ucs_K_L = {f(ucs.K_L)}")
    L.append(f"    public static let cam16ucs_c_1 = {f(ucs.c_1)}")
    L.append(f"    public static let cam16ucs_c_2 = {f(ucs.c_2)}")
    L.append("}")
    L.append("")
    return "\n".join(L)


# Transfer-function tag per colourspace. Implemented as formulas in Swift
# (Sources/SpektraFilm/Colour/TransferFunction.swift) and golden-gated against
# colour-science, so these are labels, not data.
TRANSFER = {
    "sRGB": "sRGB",
    "DCI-P3": "gamma26",
    "Display P3": "sRGB",
    "Adobe RGB (1998)": "adobeRGB",
    "ITU-R BT.2020": "bt2020",
    "ProPhoto RGB": "proPhoto",
    "ACES2065-1": "linear",
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = ap.parse_args()

    generated = build()
    if args.check:
        if not OUT.exists():
            print(f"missing {OUT.relative_to(REPO)}", file=sys.stderr)
            return 1
        if OUT.read_text() != generated:
            print(
                f"{OUT.relative_to(REPO)} is stale — run `make tables`",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT.relative_to(REPO)} up to date")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(generated)
    print(f"wrote {OUT.relative_to(REPO)} ({len(generated.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
